# Generated by Django 4.1.7 on 2023-04-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseño',
            name='fechaPost',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
